name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:

  build:

    name: build-Project

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code

      uses: actions/checkout@v2

    - name: install node 20

      uses: actions/setup-node@v1
        
      with: 

          node-version: 20.x

    - name: npm install dependencies
    
      run: npm i

    - name: Build project

      run: npm run build

    - name: upload artifact in oroder to deploy

      uses: actions/upload-artifact@v2

      with:

        name: production-files

        path: ./build

  deploy:

    name: deploy-project
    
    runs-on: ubuntu-latest

    needs: build

    steps:
      
      - name: Dowload artifact

        uses: actions/download-artifact@v2

        with:

          name: production-files

          path: ./build

      - name: deploying into gh pages

        uses: peaceiris/actions-gh-pages@v3

        with:

          github_token: ${{secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}

          publish_dir: ./build

