name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with: 
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1
        with:
          channel: '#your-channel'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: 'Build was successful! :tada:'

      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1
        with:
          channel: '#your-channel'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: 'Build failed. :x:'

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Notify Slack on Deployment Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1
        with:
          channel: '#your-channel'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: 'Deployment to GitHub Pages was successful! :rocket:'

      - name: Notify Slack on Deployment Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1
        with:
          channel: '#your-channel'
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: 'Deployment to GitHub Pages failed. :warning:'

